from typing import List, Optional
from ...domain.models.document import Block
from ...domain.evidence.core import (
    BaseEvidence, TextEvidence, TableEvidence, 
    FigureEvidence, FormulaEvidence, EmbeddedImageEvidence, LinkEvidence,
    PhysicalLayoutEvidence, LogicalStructureEvidence, SectionEvidence, ParagraphEvidence, HeadingEvidence,
    ListEvidence, CaptionEvidence, FootnoteEvidence, ReferenceEvidence,
    ReadingOrderEvidence
)

class BlockBuilder:
    def build_from_evidence(self, evidence: BaseEvidence) -> Optional[Block]:
        block_id = evidence.evidence_id
        
        if isinstance(evidence, TextEvidence):
            return Block(block_id=block_id, content=evidence.text, block_type="text")
        elif isinstance(evidence, TableEvidence):
            # Converting table rows back to simple text for block, actual HTML would be generated by Exporter
            content = f"Table({len(evidence.rows)} rows)"
            return Block(block_id=block_id, content=content, block_type="table")
        elif isinstance(evidence, FormulaEvidence):
            return Block(block_id=block_id, content=evidence.latex, block_type="formula")
        elif isinstance(evidence, FigureEvidence):
            return Block(block_id=block_id, content=f"Figure(caption={evidence.caption})", block_type="figure")
        elif isinstance(evidence, EmbeddedImageEvidence):
            return Block(block_id=block_id, content=f"EmbeddedImage(width={evidence.width}, height={evidence.height}, ext={evidence.ext})", block_type="embedded_image")
        elif isinstance(evidence, LinkEvidence):
            return Block(block_id=block_id, content=f"Link(url={evidence.url}, text={evidence.text})", block_type="link")
        elif isinstance(evidence, PhysicalLayoutEvidence):
            return Block(block_id=block_id, content=f"PhysicalLayout({evidence.layout_type}, {evidence.content})", block_type="physical_layout")
        elif isinstance(evidence, LogicalStructureEvidence):
            return Block(block_id=block_id, content=f"LogicalStructure({evidence.structure_type}, {evidence.content})", block_type="logical_structure")
        elif isinstance(evidence, SectionEvidence):
            return Block(block_id=block_id, content=f"Section({evidence.level}: {evidence.title})", block_type="section")
        elif isinstance(evidence, ParagraphEvidence):
            return Block(block_id=block_id, content=evidence.text, block_type="paragraph")
        elif isinstance(evidence, HeadingEvidence):
            return Block(block_id=block_id, content=f"Heading({evidence.level}: {evidence.text})", block_type="heading")
        elif isinstance(evidence, ListEvidence):
            return Block(block_id=block_id, content=f"List(items={len(evidence.items)}, ordered={evidence.is_ordered})", block_type="list")
        elif isinstance(evidence, CaptionEvidence):
            return Block(block_id=block_id, content=f"Caption({evidence.text})", block_type="caption")
        elif isinstance(evidence, FootnoteEvidence):
            return Block(block_id=block_id, content=f"Footnote({evidence.marker}: {evidence.text})", block_type="footnote")
        elif isinstance(evidence, ReferenceEvidence):
            return Block(block_id=block_id, content=f"Reference({evidence.citation_marker}: {evidence.text})", block_type="reference")
        elif isinstance(evidence, ReadingOrderEvidence):
            return Block(block_id=block_id, content=f"ReadingOrder({len(evidence.nodes)} nodes)", block_type="reading_order")
        return None
